spring:
  application:
    name: checkpoints-api-gateway
  cloud:
    gateway:
      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedHeaders: "*"
#            allowedMethods: "*"
#            allowCredentials: true
